### ISSUE TITLE
 Error: Field '_scrollController' should be initialized because its type 'ScrollController' doesn't allow null.  - 'ScrollController' is from 'package:flutter/src/widgets/scroll_controller.dart' ('../../flutter/packages/flutter/lib/src/widgets/scroll_controller.dart').  ScrollController _scrollController;

### ISSUE THREAD

**Issue by nabilnazar** [hadikachmar3/Udemy_Store_app#1]
![image](https://user-images.githubusercontent.com/32013563/140615796-3d86e96b-3a64-4da8-a154-4d242dbae117.png)

**Comment by hadikachmar3** [comment]
Hello, 

It's about null safety, simple add late to it will work because we initialize it in the initState.

You should know about the null safety or work with Flutter 1.22 sdk
Please watch this video to know more about variable initialization in Flutter 2.0+
https://youtu.be/fN1oYFV_xc8
![scroll controller null safety](https://user-images.githubusercontent.com/38382273/140623107-9bf4c4c4-7abe-4076-807e-efcea999e2a0.jpeg)


Best regards
Hadi
